// Code generated by " ../../../../github.com/grailbio/base/gtl/generate.py --PREFIX=simpleStruct12 --package=gql --output=struct12.go -DNN=12 struct.go.tpl ". DO NOT EDIT.

package gql

// A template for a struct with a fixed number of fields.
// Template parameters:
//
// 12: number of fields, as an integer.
//
// Example:
// $GRAIL/go/src/github.com/base/grailbio/base/gtl/generate.py --prefix=struct5 --package=gql --output=struct5.go -D12=5 struct.go.tpl

import "github.com/grailbio/gql/symbol"

// Len implements Struct
func (s *simpleStruct12Impl) Len() int { return s.nFields }

// Field implements Struct
func (s *simpleStruct12Impl) Field(i int) StructField { return StructField{s.names[i], s.values[i]} }

// Value implements Struct
func (s *simpleStruct12Impl) Value(colName symbol.ID) (Value, bool) {
	for i := 0; i < s.nFields; i++ {
		if s.names[i] == colName {
			return s.values[i], true
		}
	}
	return Value{}, false
}

var _ Struct = &simpleStruct12Impl{}

type simpleStruct12Impl struct {
	StructImpl
	nFields int
	names   [12]symbol.ID // symbol.ID is 32bit, so pack it from values.
	values  [12]Value
}
