// Code generated by "stringer -type ValueType value_type.go"; DO NOT EDIT.

package gql

import "strconv"

const _ValueType_name = "InvalidTypeNullTypeBoolTypeIntTypeFloatTypeStringTypeFileNameTypeEnumTypeCharTypeDateTypeDateTimeTypeDurationTypeUnusedTypeStructTypeStructFragmentTypeTableTypeFuncType"

var _ValueType_index = [...]uint8{0, 11, 19, 27, 34, 43, 53, 65, 73, 81, 89, 101, 113, 123, 133, 151, 160, 168}

func (i ValueType) String() string {
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
